"""auto-generate Votes table

Revision ID: fd804c64d51e
Revises: 529d05f73812
Create Date: 2023-07-28 16:48:20.097783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd804c64d51e'
down_revision = '529d05f73812'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Post_id'], ['Posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['User_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('User_id', 'Post_id')
    )


def downgrade() -> None:
    op.drop_table('Votes')
    # ### end Alembic commands ###
